# Generated by Django 4.2.1 on 2023-05-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sectora',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('plot_no', models.FloatField(blank=True, null=True)),
                ('street_no_field', models.CharField(blank=True, db_column='street_no_', max_length=50, null=True)),
                ('id', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('plotsize', models.FloatField(blank=True, null=True)),
                ('areamarla', models.FloatField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='propsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sector', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('plotid', models.IntegerField()),
                ('plotnum', models.CharField(max_length=20)),
            ],
        ),
    ]
