# Generated by Django 4.2.1 on 2023-05-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_sectora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectora',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('plot_no', models.FloatField(blank=True, null=True)),
                ('street_no_field', models.CharField(blank=True, db_column='street_no_', max_length=50, null=True)),
                ('id', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('plotsize', models.FloatField(blank=True, null=True)),
                ('areamarla', models.FloatField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
